services:
  app:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/video-index/run.py
    image: ghcr.io/williamjacksn/video-index
    init: true
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/python/video-index
    working_dir: /home/python/video-index

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/video-index
    init: true
    volumes:
      - ./:/home/python/video-index
    working_dir: /home/python/video-index
